name: Zig Build and Lint

on:
  push: {}

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        zig_version: ['0.13.0']
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: ${{ matrix.zig_version }}
      - name: Install OpenGL and glfw (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install libglew-dev libglfw3 libglfw3-dev
      - name: Install glfw (macOS)
        if: runner.os == 'macOS'
        run: brew install glfw
      - name: Build the project
        run: zig build
      - name: Upload binary
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: project-name-${{ runner.os }}
          path: zig-out/*

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: '0.13.0'
      - run: zig fmt --check .